require('plugins')
require('settings')
require('keymaps')
require('colorscheme')
require('completion')
require("lsp")
require("treesitter")
require("autopairs")
require("comment")
require("nvimtree")
require("buffer-line") -- file name should different from plugin name
